- id: assert-news
  name: Assert news files
  description: Assert that a news file has been added and describes the change.
  entry: cd-assert-news -l
  language: python
  types: [file]
  require_serial: true
  verbose: true
  always_run: true
  pass_filenames: false    
- id: licensing
  name: licensing
  entry: cd-license-files
  language: python
  types: [file]
  require_serial: true
  always_run: true
  verbose: true
  pass_filenames: false