#
# Copyright (C) 2020-2025 Arm Limited or its affiliates and Contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "3.2.1"
COMMIT = "516e08deffc6bba1a9fd975f52587189e19ef5aa"
MAJOR = 3
MINOR = 2
PATCH = 1
