#
# Copyright (C) 2020-2026 Arm Limited or its affiliates and Contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""

__version__ = "3.5.1"
COMMIT = "5f0dc45967d1e56a6e03168c0c9b54cc7aaa98c7"
MAJOR = 3
MINOR = 5
PATCH = 1
