#
# Copyright (C) 2020-2022 Arm Limited or its affiliates and Contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "3.0.0"
COMMIT = "ce55582d57532f7b08463b6ccee1b84f6f3239f3"
MAJOR = 3
MINOR = 0
PATCH = 0
