#
# Copyright (c) 2020, Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "1.5.0"
COMMIT = "61535bda142824fe261d1e61ce5c14f588810230"
MAJOR = 1
MINOR = 5
PATCH = 0
