#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "1.6.1"
COMMIT = "e74fd04fb6bb04c9ac303f764ec0e3da539e5868"
MAJOR = 1
MINOR = 6
PATCH = 1
