"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "1.3.0"
COMMIT = "a50cc682fe00c2e01aaafd4a94e9158c5905734c"
MAJOR = 1
MINOR = 3
PATCH = 0
