name: "Run type checker"
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version ${{inputs.python-version}}
      - name: Install pipenv
        shell: bash
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --system --dev
      - name: Type check with mypy
        run: |
          mypy .